"""
Shared data loading utilities for ML training scripts.

Data source priority:
  1. Azure Blob Storage (production — uploaded by load_kaggle_data.py or CI/CD)
  2. Local tasks_data.csv (generated from real Kaggle data via load_kaggle_data.py)
  3. Synthetic fallback (generated by generate_sample_data.py)
"""
import os
from io import BytesIO

import pandas as pd
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", "backend", ".env"))

ML_DIR = os.path.dirname(os.path.abspath(__file__))
PRIORITY_MAP = {"High": 3, "Medium": 2, "Low": 1}

# Minimum row count to consider a dataset valid for training
MIN_TRAINING_ROWS = 100


def load_data_from_blob(blob_name: str = "tasks_data.csv") -> pd.DataFrame:
    """Download a CSV from Azure Blob Storage."""
    from azure.storage.blob import BlobServiceClient

    conn_str = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
    container = os.getenv("AZURE_STORAGE_CONTAINER", "tododata")

    blob_service = BlobServiceClient.from_connection_string(conn_str)
    blob_client = blob_service.get_blob_client(container=container, blob=blob_name)
    stream = blob_client.download_blob().readall()
    return pd.read_csv(BytesIO(stream))


def load_data_local(filename: str = "tasks_data.csv") -> pd.DataFrame:
    """Load local CSV. Prefers real Kaggle-derived data over synthetic."""
    local_path = os.path.join(ML_DIR, filename)
    if os.path.exists(local_path):
        df = pd.read_csv(local_path)
        if len(df) >= MIN_TRAINING_ROWS:
            source = "real Kaggle-derived" if len(df) > 500 else "local"
            print(f"Loaded {source} data: {len(df)} rows")
            return df
    raise FileNotFoundError(
        f"No valid {filename} found. Run 'python load_kaggle_data.py' "
        f"(preferred) or 'python generate_sample_data.py' (fallback)."
    )


def load_data(blob_name: str = "tasks_data.csv") -> pd.DataFrame:
    """Try Azure Blob first, fall back to local CSV."""
    try:
        df = load_data_from_blob(blob_name)
        print(f"Loaded data from Azure Blob Storage ({len(df)} rows)")
        return df
    except Exception as e:
        print(f"Azure Blob not available ({e}) — using local CSV")
        return load_data_local(blob_name)
